### ISSUE TITLE
Ejemplo de protocolo MQTT con yubox-node

### ISSUE THREAD

**Issue by alejo-jose** [yubox-node-org/yubox-now#1]
Hola, me podrian ayudar con un ejemplo del protocolo MQTT en yubox-node

**Comment by avillacis** [comment]
Intente con el ejemplo de MQTT que se ha publicado en el commit https://github.com/yubox-node-org/yubox-now/commit/9e8919ee2a7382573dcafac11ecf4d387cc24163 . Espero que le ayude.

**Comment by alejo-jose** [comment]
Muchas gracias, ya lo reviso
